#!/bin/bash

if [ -f $1 ]
then
  vim $1
  exit $?
fi

if [ $# -eq 0 ]
then
        exit
fi

f=($(find . -name $1))
fname=${f[0]}

numfiles=${#f[*]}
if [ $numfiles -gt 1 -a -z "$2" ]
then
  echo Files
  a=0
  for i in ${f[*]}
  do
    ((a=a+1))
    echo $a - $i
  done
  exit $a
elif [ $numfiles -gt 1 ]
then
  fname=${f[(($numfiles-1))]}
fi

if [ ! -f "$fname" ]
then
    echo $fname not found.
    exit 1
fi

echo $fname

vim $fname
